### PR TITLE
Link naar inkoopboeking toegevoegd aan InkoopfactuurModel.

### PR DESCRIPTION
**Pull request by pdebruine**

### CODE REVIEW

**Comment by pdebruine** [comment]
@snelstart @tvandegraaf can somebody please check this pull request and merge it if possible?

**Comment by tvandegraaf** [comment]
@pdebruine I'm sorry, I did not get notified about your PR. Let me fix the casing since apparently we chose to make use of an uppercase B. Then I'll approve this PR. Thank you for your support!

**Comment by pdebruine** [comment]
@tvandegraaf Hi Tom, thanks for merging. I noticed there is no new nuget release for the client and the Azure Pipelines says failed on the main page. Should the nuget be created automatically?

**Comment by tvandegraaf** [comment]
@pdebruine We had some trouble with releasing a new version of our NuGet package to the NuGet feed. Another build is running as we speak which should push a new version to NuGet soon. My apologies.

**Pull request merged**
